package com.example.myapplication.CourseFactory;

public enum CourseType {
    POGO, HIST, THES, ENVS, MEDN, TOKP, SCOM, ANIP, ARAB, COMP, POPH, POPM, EMDV, ACST, PASI, SCNC,
    CBEA, MATH, HONS, ASTR, LAWS, GEND, PHYS, MEDI, PHIL, ECHI, INTR, CLAS, ARCH, INDG, ANCH, HUMN,
    VCPG, EXTN, INDN, CECS, FREN, CHIN, HIND, HLTH, TURK, CRWF, DIPL, MNGL, PSYC, SPAN, ARTV, ENGL,
    ARTS, BAPA, ENGN, STAT, EMET, BIOL, ARTH, REGN, ANTH, PPEI, DESN, VIET, LATN, TETM, INFS, DESA,
    INFT, CHST, MMIB, NSPO, CHMD, WARS, PORT, STST, TIBN, JPNS, SCRN, BIAN, NEUR, ITAL, KORE, MKTG,
    GERM, THAI, SKRT, RUSS, CRIM, EURO, LANG, BURM, CHEM, PERS, ASIA, LING, BPHB, VCUG, EMSC, MUSI,
    IDEC, MUSC, ECON, FINM, POLS, MGMT, SOCR, MEAS, GREK, BUSN, SOCY, BUSI, DEMO
}
